version: "3.5"
services:
  ${DOCKER_CONTAINER_NAME}:
    image: ${DOCKER_IMAGE_REPO}:${DOCKER_IMAGE_TAG}
    container_name: ${DOCKER_CONTAINER_NAME}
    user: 1000:1000
    network_mode: "host"
    cgroup_parent: "${DOCKER_CGROUP_PARENT}"
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - /data/INTERNAL:/VOLUMIO/INTERNAL
      - type: bind
        source: /mnt/NAS
        target: /VOLUMIO/NAS
        bind:
          propagation: slave
      - type: bind
        source: /media
        target: /VOLUMIO/USB
        bind:
          propagation: slave
    restart: "no"
volumes:
  jellyfin-config:
    external: true
  jellyfin-cache:
    external: true
